---
- name: "Installing dconf dependencies"
  apt:
    name: python-psutil
    update_cache: yes
    state: present

- name: "Setting desktop background"
  become: true
  become_user: "{{ username }}"
  dconf:
    key: /org/gnome/desktop/background/picture-uri
    value: "'file:///usr/share/backgrounds/nord-dark.png'"
    state: present
  ignore_errors: true

- name: "Setting screensaver background"
  become: true
  become_user: "{{ username }}"
  dconf:
    key: /org/gnome/desktop/screensaver/picture-uri
    value: "'file:///usr/share/backgrounds/nord-dark.png'"
    state: present
  ignore_errors: true

- name: "Retrieving unused backgrounds"
  find:
    paths:
      - /usr/share/backgrounds
    file_type: file
    excludes:
      - ESP_016895_1525_desktop.jpg
      - ESP_020528_1750_desktop.jpg
      - joel-filipe-unsplash.jpg
      - luca-bravo-xnqVGsbXgV4-unsplash.jpg
      - nord-dark.png
      - regolith-structure-7.png
  register: backgrounds

- name: "Removing unused backgrounds"
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ backgrounds['files'] }}"
