---
- name: Set timezone to europe/amsterdam
  community.general.timezone:
    name: Europe/Amsterdam

- name: Set hardware clock to local
  community.general.timezone:
    hwclock: local

- name: Configure timesync
  copy:
    src: timesync/timesyncd.conf
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: 0644

- name: Restart timesync
  service:
    name: systemd-timesyncd
    state: restarted
    enabled: true
  changed_when: false
