---
- name: Add zoom key
  apt_key:
    url: https://zoom.us/linux/download/pubkey
    keyring: /etc/apt/trusted.gpg.d/zoom.gpg
    state: present

- name: Install zoom
  apt:
    deb: https://zoom.us/client/latest/zoom_amd64.deb
    state: present
