---
- name: Add microsoft key
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/microsoft.gpg
    state: present

- name: Add microsoft repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/ubuntu/20.04/prod focal main
    filename: microsoft
    state: present

- name: Install dotnet
  ansible.builtin.apt:
    name:
      - dotnet-sdk-{{ csharp.version }}
      - aspnetcore-runtime-{{ csharp.version }}
      - dotnet-runtime-{{ csharp.version }}
    update_cache: true
    state: latest
