---
- hosts: localhost
  become: true
  roles:
    - common/curl
    - common/dig
    - common/exfat
    - common/git
    - common/make
    - common/nmap
    - common/time
    - common/tweaks
    - common/unzip
    - common/wget
    - boot/grub
    - browsing/chrome
    - browsing/firefox
    - communication/discord
    - communication/slack
    - drivers/nvidia
    - drivers/wireless
    - media/spotify
    - power/intel
    - power/powertop
