---
- hosts: localhost
  become: true
  roles:
    - common/curl
    - common/dig
    - common/exfat
    - common/git
    - common/make
    - common/neofetch
    - common/net-tools
    - common/nmap
    - common/time
    - common/tweaks
    - common/unzip
    - common/wget
    - boot/grub
    - browsing/chrome
    - browsing/firefox
    - communication/discord
    - communication/slack
    - drivers/nvidia
    - drivers/wireless
    - media/spotify
    - power/intel
    - power/powertop
    - power/tlp
    - tools/mongo
    - tools/ngrok
    - tools/postgres
    - tools/postman
    - tools/vpn
    - tools/wireshark
    - development/android
    - development/clojure
    - development/code
    - development/csharp
    - development/dart
    - development/docker
    - development/golang
    - development/java
    - development/javascript
    - development/python
    - development/rust
    - development/vagrant
    - interface/background
    - interface/cleanup
    - interface/screen
    - common/config
    - common/permissions
