---
- hosts: workstation
  become: true
  pre_tasks:
    - name: Update & upgrade packages
      apt:
        name: "*"
        update_cache: true
        state: latest
  roles:
    - common/curl
    - common/dig
    - common/disks
    - common/exfat
    - common/git
    - common/lfs
    - common/make
    - common/net-tools
    - common/nmap
    - common/time
    - common/tweaks
    - common/unzip
    - common/wget
    - boot/grub
    - browsing/chrome
    - browsing/firefox
    - communication/discord
    - communication/slack
    - communication/teams
    - communication/zoom
    - drivers/intel
    - drivers/nvidia
    - media/shotwell
    - media/spotify
    - power/powertop
    - power/tlp
    - tools/dbeaver
    - tools/graphviz
    - tools/mongo
    - tools/ngrok
    - tools/postgres
    - tools/vpn
    - tools/wireshark
    - development/android
    - development/clojure
    - development/code
    - development/csharp
    - development/dart
    - development/docker
    - development/golang
    - development/java
    - development/javascript
    - development/python
    - development/r
    - development/rust
    - development/vagrant
    - interface/cleanup
    - interface/login
    - interface/screen
    - common/config
    - common/permissions
