---
- name: Workstation Playbook
  hosts: workstation
  become: true
  pre_tasks:
    - name: Update & upgrade packages
      ansible.builtin.apt:
        name: "*"
        update_cache: true
        state: latest
  roles:
    - common/curl
    - common/dig
    - common/disks
    - common/exfat
    - common/git
    - common/lfs
    - common/make
    - common/net-tools
    - common/nmap
    - common/time
    - common/unzip
    - common/wget
    - boot/grub
    - browsing/chrome
    - browsing/firefox
    - communication/discord
    - communication/signal
    - communication/slack
    - drivers/intel
    - drivers/nvidia
    - media/shotwell
    - media/spotify
    - power/powertop
    - power/tlp
    - tools/aws
    - tools/az
    - tools/gcp
    - tools/imager
    - tools/ngrok
    - tools/onlyoffice
    - tools/postgres
    - tools/vpn
    - development/code
    - development/docker
    - development/golang
    - development/javascript
    - development/packer
    - development/python
    - development/terraform
    - development/vagrant
    - interface/cleanup
    - interface/login
    - interface/screen
    - common/config
    - common/permissions
