---
- name: Add cuda key
  apt_key:
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
    keyring: /etc/apt/trusted.gpg.d/cuda.gpg
    state: present

- name: Add cuda repository
  apt_repository:
    repo: deb [arch=amd64] http://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64 /
    filename: cuda
    state: present

- name: Pin cuda repository
  copy:
    src: cuda/cuda-repository-pin-600
    dest: /etc/apt/preferences.d/cuda-pin-600
    owner: root
    group: root
    mode: 0644

- name: Install nvidia driver
  apt:
    name:
      - nvidia-driver-460
      - nvidia-settings
    state: latest

- name: Install cuda driver
  apt:
    name:
      - cuda
      - nvidia-cuda-toolkit
    update_cache: true
    state: latest

- name: Install cudnn library
  unarchive:
    src: cudnn/cudnn-v8.1.1.tgz
    dest: /usr/lib
    creates: /usr/lib/cuda/include/cudnn.h
