---
- name: "Adding backport-iwlwifi repository"
  apt_repository:
    repo: ppa:canonical-hwe-team/backport-iwlwifi
    filename: backport-iwlwifi
    state: present

- name: "Installing backport-iwlwifi driver"
  apt:
    name: backport-iwlwifi-dkms
    update_cache: true
    state: present
