---
- name: Install r dependencies
  apt:
    name:
      - libssl-dev
      - libcurl4-openssl-dev
    state: latest

- name: Add r key
  apt_key:
    id: E298A3A825C0D65DFD57CBB651716619E084DAB9
    keyserver: keyserver.ubuntu.com
    keyring: /etc/apt/trusted.gpg.d/r.gpg
    state: present

- name: Add r repository
  apt_repository:
    repo: deb [arch=amd64] https://cloud.r-project.org/bin/linux/ubuntu focal-cran{{ r.version | replace('.', '') }}/
    filename: r
    state: present

- name: Install r
  apt:
    name: r-base
    update_cache: true
    state: latest

- name: Add rstudio key
  apt_key:
    id: 3F32EE77E331692F
    keyserver: keys.gnupg.net
    keyring: /etc/apt/trusted.gpg.d/rstudio.gpg
    state: present
  when: r.studio.enabled

- name: Install rstudio
  apt:
    deb: https://download1.rstudio.org/desktop/bionic/amd64/rstudio-{{ r.studio.version }}-amd64.deb
    state: present
  when: r.studio.enabled

- name: Install rstudio theme
  copy:
    src: rstudio/nord.rstheme
    dest: /home/{{ ansible_user }}/.config/rstudio/themes/
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
