---
- name: Add r key
  apt_key:
    id: E298A3A825C0D65DFD57CBB651716619E084DAB9
    keyserver: keyserver.ubuntu.com
    keyring: /etc/apt/trusted.gpg.d/r.gpg
    state: present

- name: Add r repository
  apt_repository:
    repo: deb [arch=amd64] https://cloud.r-project.org/bin/linux/ubuntu focal-cran{{ r.version | replace('.', '') }}/
    filename: r
    state: present

- name: Install r
  apt:
    name: r-base
    update_cache: true
    state: latest
