---
- name: Remove unused applications
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - htop
    - vim
    - xterm

- name: Hide internal applications
  lineinfile:
    path: /usr/share/applications/{{ item }}
    line: NoDisplay=true
    state: present
    create: true
  with_items:
    - compton.desktop
    - org.regolith-linux.remontoire.desktop
    - regolith.desktop
