---
- name: Remove unused applications
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - htop
    - vim
    - xterm

- name: Hide internal applications
  ansible.builtin.lineinfile:
    path: /usr/share/applications/{{ item }}
    line: NoDisplay=true
    owner: root
    group: root
    mode: "0644"
    state: present
    create: true
  with_items:
    - compton.desktop
    - org.regolith-linux.remontoire.desktop
    - regolith.desktop
