---
- name: Install tlp
  ansible.builtin.apt:
    name:
      - tlp
      - tlp-rdw
    state: latest

- name: Find default tlp config
  ansible.builtin.find:
    paths:
      - /etc/tlp.d
    file_type: file
    excludes:
      - 00-operation.conf
  register: config

- name: Remove default tlp config
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ config.files }}"

- name: Configure tlp
  ansible.builtin.copy:
    src: tlp/
    dest: /etc/tlp.d/
    owner: root
    group: root
    mode: "0644"

- name: Enable tlp
  ansible.builtin.service:
    name: tlp
    state: started
    enabled: true
