---
- name: Install bun (linux)
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  block:
    - name: Get bun release (linux)
      ansible.builtin.uri:
        url: https://api.github.com/repos/oven-sh/bun/releases/latest
        return_content: true
      register: bun_release

    - name: Create bun directory (linux)
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/.bun/bin
        state: directory
        mode: "0755"

    - name: Download bun (linux)
      ansible.builtin.unarchive:
        src: https://github.com/oven-sh/bun/releases/download/{{ bun_release.json.tag_name }}/bun-linux-x64.zip
        dest: /tmp
        remote_src: true

    - name: Install bun (linux)
      ansible.builtin.copy:
        src: /tmp/bun-linux-x64/bun
        dest: /home/{{ ansible_user }}/.bun/bin/bun
        mode: "0755"
        remote_src: true

- name: Install bun (macos)
  community.general.homebrew:
    name: bun
    state: latest
  when: ansible_distribution == 'MacOSX'
