---
- name: Install netbird (linux)
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  block:
    - name: Add netbird repository (linux)
      ansible.builtin.deb822_repository:
        name: netbird
        types: [deb]
        uris: [https://pkgs.netbird.io/debian]
        suites: [stable]
        components: [main]
        architectures: [amd64]
        signed_by: https://pkgs.netbird.io/debian/public.key
        state: present

    - name: Install netbird (linux)
      ansible.builtin.apt:
        name: netbird
        update_cache: true
        state: latest

- name: Install netbird (macOS)
  when: ansible_distribution == 'MacOSX'
  block:
    - name: Download netbird pkg (macos)
      ansible.builtin.get_url:
        url: https://pkgs.netbird.io/macos/{{ 'arm64' if ansible_machine == 'arm64' else 'amd64' }}
        dest: /tmp/netbird.pkg
        mode: "0644"

    - name: Install netbird pkg (macos)
      become: true
      ansible.builtin.command:
        cmd: installer -pkg /tmp/netbird.pkg -target /
      changed_when: true

    - name: Remove netbird pkg (macos)
      ansible.builtin.file:
        path: /tmp/netbird.pkg
        state: absent

- name: Disable netbird ssh config
  become: true
  ansible.builtin.command:
    cmd: netbird service reconfigure --service-env NB_DISABLE_SSH_CONFIG=true
  changed_when: false
