---
- name: Install weka
  unarchive:
    src: https://netix.dl.sourceforge.net/project/weka/weka-{{ weka.version[:3] | replace('.','-') }}/{{ weka.version }}/weka-{{ weka.version | replace('.','-') }}-azul-zulu-linux.zip
    dest: /opt
    remote_src: true
    creates: /opt/weka

- name: Rename weka
  command:
    cmd: mv /opt/weka-{{ weka.version | replace('.','-') }} /opt/weka
    creates: /opt/weka

- name: Move weka script
  command:
    cmd: mv /opt/weka/weka.sh /usr/bin/weka
    creates: /usr/bin/weka

- name: Update weka script
  lineinfile:
    path: /usr/bin/weka
    regexp: ^DIR
    line: DIR="/opt/weka"
    state: present

- name: Add weka icon
  copy:
    src: weka/weka.png
    dest: /usr/share/pixmaps/weka.png
    owner: root
    group: root
    mode: 0644

- name: Add weka application
  copy:
    src: weka/weka.desktop
    dest: /usr/share/applications/weka.desktop
    owner: root
    group: root
    mode: 0644
