---
- name: Add regolith repository
  ansible.builtin.apt_repository:
    repo: ppa:regolith-linux/release
    filename: regolith-linux-ubuntu-release-focal
    state: present

- name: Install regolith looks
  ansible.builtin.apt:
    name:
      - regolith-look-ayu
      - regolith-look-ayu-dark
      - regolith-look-ayu-mirage
      - regolith-look-cahuella
      - regolith-look-lascaille
      - regolith-look-nord
      - regolith-look-solarized-dark
      - regolith-look-ubuntu
    state: latest

- name: Install i3xrocks extensions
  ansible.builtin.apt:
    name:
      - i3xrocks-battery
      - i3xrocks-cpu-usage
      - i3xrocks-memory
      - i3xrocks-net-traffic
      - i3xrocks-time
    state: latest
