---
- name: Download rust install script
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rust.sh
    mode: 0755

- name: Install rust
  command: /tmp/rust.sh -y --no-modify-path
  environment:
    CARGO_HOME: /home/{{ ansible_user }}/.cargo
    RUSTUP_HOME: /home/{{ ansible_user }}/.rustup
  changed_when: "'installing' in cmd.stdout"
  register: cmd
