---
- name: Install wireshark
  apt:
    name: wireshark
    state: latest

- name: Configure wireshark
  debconf:
    name: wireshark-common
    question: wireshark-common/install-setuid
    value: "true"
    vtype: boolean

- name: Reconfigure wireshark
  command: dpkg-reconfigure -f noninteractive wireshark-common
  changed_when: false

- name: Set dumpcap group to wireshark
  file:
    path: /usr/bin/dumpcap
    group: wireshark
    mode: 0754
    state: file

- name: Set cap to dumpcap
  command: setcap -v cap_net_raw,cap_net_admin=eip /usr/bin/dumpcap
  changed_when: false

- name: Add user to wireshark group
  user:
    name: "{{ ansible_user }}"
    groups:
      - wireshark
    append: true
