---
- name: "Adding wireshark repository"
  apt_repository:
    repo: ppa:wireshark-dev/stable
    filename: wireshark
    state: present

- name: "Installing wireshark"
  apt:
    name: wireshark
    update_cache: true
    state: present

- name: "Configuring wireshark"
  debconf:
    name: wireshark-common
    question: wireshark-common/install-setuid
    value: "true"
    vtype: boolean

- name: "Reconfigure wireshark"
  command: dpkg-reconfigure -f noninteractive wireshark-common
  changed_when: false

- name: "Changing group for dumpcap binary"
  file:
    path: /usr/bin/dumpcap
    group: wireshark
    mode: "750"
    state: file

- name: "Setting cap to dumpcap"
  command: setcap cap_net_raw,cap_net_admin=eip /usr/bin/dumpcap
  changed_when: false

- name: "Adding user to the wireshark group"
  user:
    name: "{{ username }}"
    groups:
      - wireshark
    append: true
