---
- name: Check if repository exists
  stat:
    path: /home/{{ ansible_user }}/.git
  register: git

- name: Initialize repository
  command:
    cmd: git init
    chdir: /home/{{ ansible_user }}
  when: not git.stat.exists

- name: Set git remote to {{ config.repository }}
  command:
    cmd: git remote add origin {{ config.repository }}
    chdir: /home/{{ ansible_user }}
  when: not git.stat.exists

- name: Fetch origin
  command:
    cmd: git fetch origin
    chdir: /home/{{ ansible_user }}
  when: not git.stat.exists

- name: Reset to latest version of master
  command:
    cmd: git reset origin/master --hard
    chdir: /home/{{ ansible_user }}
  when: not git.stat.exists
