---
- name: Check if repository exists
  ansible.builtin.stat:
    path: /home/{{ ansible_user }}/.git
  register: git

- name: Initialize repository
  ansible.builtin.command: # noqa: command-instead-of-module no-changed-when
    cmd: git init
    chdir: /home/{{ ansible_user }}
  when: not git.stat.exists

- name: Set git remote to {{ config.repository }}
  ansible.builtin.command: # noqa: command-instead-of-module no-changed-when
    cmd: git remote add origin {{ config.repository }}
    chdir: /home/{{ ansible_user }}
  when: not git.stat.exists

- name: Fetch origin
  ansible.builtin.command: # noqa: command-instead-of-module no-changed-when
    cmd: git fetch origin
    chdir: /home/{{ ansible_user }}
  when: not git.stat.exists

- name: Reset to latest version of master
  ansible.builtin.command: # noqa: command-instead-of-module no-changed-when
    cmd: git reset origin/master --hard
    chdir: /home/{{ ansible_user }}
  when: not git.stat.exists
