---
- name: Install git (linux)
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  block:
    - name: Install git (linux)
      ansible.builtin.apt:
        name: git
        state: latest

# TODO: install git-filter-repo on linux

- name: Install git (macos)
  when: ansible_distribution == 'MacOSX'
  block:
    - name: Install git (macos)
      community.general.homebrew:
        name: git
        state: latest

    - name: Install git-filter-repo (macos)
      community.general.homebrew:
        name: git-filter-repo
        state: latest
