---
- name: Install android dependencies
  apt:
    name: openjdk-8-jdk
    state: latest

- name: Create android directory
  file:
    path: /opt/android
    state: directory

- name: Create android tools directory
  file:
    path: /opt/android/cmdline-tools
    state: directory

- name: Install android tools
  unarchive:
    src: https://dl.google.com/android/repository/commandlinetools-linux-{{ android.tools.version }}_latest.zip
    dest: /opt/android/cmdline-tools
    remote_src: true
    creates: /opt/android/cmdline-tools/latest

- name: Rename android tools
  command:
    cmd: mv /opt/android/cmdline-tools/cmdline-tools /opt/android/cmdline-tools/latest
    creates: /opt/android/cmdline-tools/latest

- name: Accept android licenses
  shell: yes | /opt/android/cmdline-tools/latest/bin/sdkmanager --sdk_root=/opt/android --verbose --licenses
  environment:
    JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
  changed_when: "'Accepted' not in cmd.stdout"
  register: cmd

- name: Install android packages
  shell: /opt/android/cmdline-tools/latest/bin/sdkmanager --sdk_root=/opt/android --verbose "{{ item }}"
  environment:
    JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
  changed_when: "'Install' in cmd.stdout"
  register: cmd
  with_items:
    - build-tools;{{ android.build.version }}
    - platforms;android-{{ android.platform.version }}
    - system-images;android-{{ android.platform.version }};google_apis;x86

- name: Add user to the plugdev & kvm group
  user:
    name: "{{ ansible_user }}"
    groups:
      - plugdev
      - kvm
    append: true
