---
- name: Install clojure dependencies
  apt:
    name:
      - rlwrap
      - default-jdk
    state: latest

- name: Download clojure install script
  get_url:
    url: https://download.clojure.org/install/linux-install-{{ clojure.version }}.sh
    dest: /tmp/clojure.sh
    mode: 0755

- name: Install clojure
  command: /tmp/clojure.sh
  changed_when: false
