---
- name: Install clojure dependencies
  ansible.builtin.apt:
    name:
      - rlwrap
      - default-jdk
    state: latest

- name: Download clojure install script
  ansible.builtin.get_url:
    url: https://download.clojure.org/install/linux-install-{{ clojure.version }}.sh
    dest: /tmp/clojure.sh
    mode: "0755"

- name: Install clojure
  ansible.builtin.command: /tmp/clojure.sh
  changed_when: false
