---
- name: Install flutter
  unarchive:
    src: https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_{{ dart.flutter.version }}-stable.tar.xz
    dest: /opt
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
    remote_src: true
    creates: /opt/flutter
  when: dart.flutter.enabled
