---
- name: Add node key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    keyring: /etc/apt/trusted.gpg.d/nodesource.gpg
    state: present

- name: Add node repository
  apt_repository:
    repo: deb [arch=amd64] https://deb.nodesource.com/node_{{ javascript.version }} focal main
    filename: nodesource
    state: present

- name: Install node
  apt:
    name: nodejs
    update_cache: true
    state: latest

- name: Install packages
  npm:
    name: "{{ item }}"
    global: true
    state: latest
  with_items: "{{ javascript.packages }}"
