---
- name: Add mendeley key
  copy:
    src: mendeley/mendeley.gpg
    dest: /etc/apt/trusted.gpg.d/mendeley.gpg
    owner: root
    group: root
    mode: 0644

- name: Add mendeley repository
  apt_repository:
    repo: deb [arch=amd64] https://desktop-download.mendeley.com/download/apt stable main
    filename: mendeley
    state: present

- name: Install mendeley
  apt:
    name: mendeleydesktop
    update_cache: true
    state: latest
