---
- name: Install opencode (linux)
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  block:
    - name: Check if opencode is installed
      ansible.builtin.stat:
        path: /home/{{ ansible_user }}/.opencode/bin/opencode
      register: opencode

    - name: Get opencode v2 formula (linux)
      ansible.builtin.uri:
        url: https://raw.githubusercontent.com/anomalyco/homebrew-tap/master/opencode-v2.rb
        return_content: true
      register: opencode_formula
      when: not opencode.stat.exists

    - name: Set opencode version (linux)
      ansible.builtin.set_fact:
        opencode_version: "{{ opencode_formula.content | regex_findall('version \"([^\"]+)\"') | first }}"
      when: not opencode.stat.exists

    - name: Create opencode directory (linux)
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/.opencode/bin
        state: directory
        mode: "0755"
      when: not opencode.stat.exists

    - name: Install opencode (linux)
      ansible.builtin.unarchive:
        src: https://opencode.ai/files/bin/{{ opencode_version }}/opencode-linux-x64.tar.gz
        dest: /home/{{ ansible_user }}/.opencode/bin
        remote_src: true
        mode: "0755"
      when: not opencode.stat.exists

- name: Install opencode (macos)
  when: ansible_distribution == 'MacOSX'
  block:
    - name: Add opencode tap (macos)
      community.general.homebrew_tap:
        name: anomalyco/tap
        state: present

    - name: Install opencode (macos)
      community.general.homebrew:
        name: anomalyco/tap/opencode-v2
        state: latest
