---
- name: Create lightdm directory
  ansible.builtin.file:
    path: /usr/share/lightdm/lightdm-gtk-greeter.conf.d
    owner: root
    group: root
    mode: "0755"
    state: directory

- name: Create background directory
  ansible.builtin.file:
    path: /usr/share/backgrounds
    owner: root
    group: root
    mode: "0755"
    state: directory

- name: Configure lightdm
  ansible.builtin.copy:
    src: lightdm/
    dest: /usr/share/lightdm/lightdm-gtk-greeter.conf.d/
    owner: root
    group: root
    mode: "0644"

- name: Download theme install script
  ansible.builtin.unarchive:
    src: https://github.com/tomdewildt/cahuella-lightdm-theme/archive/v0.1.0.zip
    dest: /tmp
    remote_src: true
    creates: /tmp/cahuella-lightdm-theme-0.1.0

- name: Install theme
  community.general.make:
    chdir: /tmp/cahuella-lightdm-theme-0.1.0
    file: Makefile
    target: install
  changed_when: false
