---
- name: Add mongo key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.4.asc
    keyring: /etc/apt/trusted.gpg.d/mongodb.gpg
    state: present

- name: Add mongo repository
  apt_repository:
    repo: deb [arch=amd64] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse multiverse
    filename: mongodb
    state: present

- name: Install mongo client
  apt:
    name: mongodb-org-shell
    update_cache: true
    state: latest
