---
- name: Install exfat (linux)
  become: true
  ansible.builtin.apt:
    name:
      - exfat-fuse
      - exfat-utils
    state: latest
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
