---
- name: Find files in home folder
  find:
    paths:
      - /home/{{ ansible_user }}
    file_type: file
    hidden: true
  register: home

- name: Set owner to {{ ansible_user }} for files in home folder
  file:
    path: "{{ item.path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: file
  with_items: "{{ home.files }}"

- name: Find directories in home folder
  find:
    paths:
      - /home/{{ ansible_user }}
    file_type: directory
    hidden: true
  register: home

- name: Set owner to {{ ansible_user }} for directories in home folder
  file:
    path: "{{ item.path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: true
    state: directory
  with_items: "{{ home.files }}"
